in_features: ${data.dataset.graph.num_nodes}  # take the number of nodes from the graph
layers: [100, 100]
dropout: null
num_transforms: 1 # number of transformations to apply (you can change)
residual: false
activation:
  _target_: torch.nn.LeakyReLU
additive: ${data.dataset.additive} # set according to the dataset
normalization:
  _target_: ocd.models.normalization.ActNorm
  _partial_: true

base_distribution:
  _target_: ${get_torch_distribution:${data.dataset.noise_generator.noise_type}}
  _args_: ${get_torch_distribution_args:${data.dataset.noise_generator.noise_type}}

ordering: null
num_post_nonlinear_transforms: 0
