defaults:
  - permutation: default
  - _self_

device: cuda
checkpointing: null


max_epochs: 500
flow_batch_size: 128
permutation_batch_size: ${.permutation.permutation_batch_size}

flow_optimizer:
  _target_: torch.optim.Adam
  lr: 0.005
  _partial_: true

permutation_optimizer: ${.flow_optimizer}

temperature: 1.0
temperature_scheduler: linear
perform_final_buffer_search: false

scheduler:
  flow_frequency: 1
  permutation_frequency: 4
  flow_lr_scheduler:
    _target_: torch.optim.lr_scheduler.ConstantLR
    _partial_: true
  permutation_lr_scheduler: ${.flow_lr_scheduler}

brikhoff: null
